spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:

server:
  port: 8888
  compression:
    enabled: true

---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

